name: Deploy Wisdom2.0 to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5


      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm install


      - name: Build React app
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_EMAIL: ${{ secrets.VITE_FIREBASE_EMAIL }}
          VITE_API_ORIGIN: ${{ secrets.VITE_API_ORIGIN }}


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist